### ISSUE TITLE
[docs] mention running SVF's "setup.sh" or similar for required environment variables

### ISSUE THREAD

**Issue by dtzWill** [unsw-corg/PTABen#1]
Minor detail :).

**Comment by dtzWill** [comment]
Oh wow, I'm blind: https://github.com/unsw-corg/PTABen/blob/master/runtest.sh#L11

While maybe it could be made more prominent, since it's clear that one needs to edit runtest.sh anyway this addresses the concern.

Apologies!

**Comment by rockysui** [comment]
Thanks Will! I will add one in PTABen homepage.
